[project]
authors = [
  {name = "darkhaniop", email = "darkhaniop@gmail.com"},
]
description = "RESTful API for HTCondor HPC job scheduler (FastAPI-based)."
dynamic = ["version"]
name = "simple-task-api-htc"
